[project]
name= "pic2base16"
version = "0.0.1"

dependencies = [
    "pillow",
    "clize",
    "pyyaml",
    "requests",
    "GitPython",
]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
pic2base16 = "pic2base16.convert:main"